# Generated by Django 4.2.23 on 2025-12-15 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("horilla_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shortcutkey",
            unique_together={("user", "key", "command")},
        ),
    ]
