# Generated by Django 4.2.23 on 2025-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horilla_core", "0004_remove_scoringcondition_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=50, verbose_name="Department Name"),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("department_name", "company")},
        ),
    ]
