# Generated by Django 4.2.23 on 2025-12-15 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("horilla_core", "0005_alter_department_department_name_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="Subject")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("meeting", "Meeting"),
                            ("task", "Task"),
                            ("log_call", "Log Call"),
                        ],
                        max_length=20,
                        verbose_name="Activity Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Source"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Related Object ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "is_all_day",
                    models.BooleanField(default=False, verbose_name="All Day"),
                ),
                (
                    "task_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "due_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Recipient Email",
                    ),
                ),
                (
                    "call_duration_display",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Call Duration",
                    ),
                ),
                (
                    "call_duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Call Duration (Seconds)"
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        blank=True,
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=50,
                        null=True,
                        verbose_name="Call Type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "call_purpose",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Call Purpose",
                    ),
                ),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Related Content Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "meeting_host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Meeting Host",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Activity Owner",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="activity_participants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participants",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "indexes": [
                    models.Index(
                        fields=["activity_type"], name="horilla_act_activit_c3097f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="horilla_act_created_5e0612_idx"
                    ),
                    models.Index(
                        fields=["status"], name="horilla_act_status_2d089e_idx"
                    ),
                    models.Index(
                        fields=["start_datetime"], name="horilla_act_start_d_43d717_idx"
                    ),
                    models.Index(
                        fields=["due_datetime"], name="horilla_act_due_dat_0f8771_idx"
                    ),
                ],
            },
        ),
    ]
