# Generated by Django 4.2.23 on 2025-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0002_alter_opportunity_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunitysplittype",
            name="split_label",
            field=models.CharField(
                help_text="Name of the split type (e.g., Revenue, Overlay)",
                max_length=255,
                verbose_name="Split Label",
            ),
        ),
    ]
